import random

i = 0
num = 1000
for i in range(0, num):
    print(i)
    r = lambda: random.randint(0, 255)
    print("Background: " + '#%02X%02X%02X' % (r(), r(), r()))
    print("")
    x = random.randint(0, 1000)
    y = random.randint(0, 1000)
    print("Square X:" + str(x) + " Y:" + str(y))
    hs = random.randint(0, 1000)
    ws = random.randint(0, 1000)
    print("Square Height:" + str(hs) + " Width:" + str(ws))
    r = lambda: random.randint(0, 255)
    print("Square Fill: " + '#%02X%02X%02X' % (r(),r(),r()))
    r = lambda: random.randint(0, 255)
    print("Square Stroke: " + '#%02X%02X%02X' % (r(), r(), r()))
    sa = random.randint(0, 360)
    print("Square degree:" + str(sa - 180))
    print("")
    z = random.randint(0, 1000)
    az = random.randint(0, 1000)
    print("Triangle X:" + str(z) + " Y:" + str(az))
    ht = random.randint(0, 1000)
    wt = random.randint(0, 1000)
    print("Triangle Height:" + str(ht) + " Width:" + str(wt))
    s = lambda: random.randint(0, 255)
    print("Triangle Fill:" + '#%02X%02X%02X' % (s(), s(), s()))
    r = lambda: random.randint(0, 255)
    print("Triangle Stroke: " + '#%02X%02X%02X' % (r(), r(), r()))
    ta = random.randint(0, 360)
    print("Triangle degree:" + str(ta - 180))
    print("")
    bz = random.randint(0, 1000)
    cz = random.randint(0, 1000)
    print("Circle X:" + str(bz) + " Y:" + str(cz))
    hc = random.randint(0, 1000)
    wc = random.randint(0, 1000)
    print("Circle Height:" + str(hc) + " Width:" + str(wc))
    t = lambda: random.randint(0, 255)
    print("Circle Fill:" + '#%02X%02X%02X' % (s(), s(), s()))
    r = lambda: random.randint(0, 255)
    print("Circle Stroke: " + '#%02X%02X%02X' % (r(), r(), r()))
    ca = random.randint(0, 360)
    print("Circle degree:" + str(ca - 180))


